const data = {
    products: [
      {
        _id: '1',
        name: 'Crispy',
        category: 'Muesli',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Crispy',
        category: 'Muesli',
        image: '/images/p2.jpg',
        price: 100,
        countInStock:20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Crispy',
        category: 'Muesli',
        image: '/images/p1.jpg',
        price: 220,
        countInStock:20,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Crispy',
        category: 'Muesli',
        image: '/images/p2.jpg',
        price: 78,countInStock:20,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Crispy',
        category: 'Muesli',
        image: '/images/p1.jpg',
        price: 65,countInStock:20,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Crispy',
        category: 'Muesli',
        image: '/images/p2.jpg',
        price: 139,countInStock:20,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;